# reference_ranges.py
# Tabla semilla de referencia clínica ajustable.
# No sustituye rangos del laboratorio ni juicio clínico.
# Se usa como base configurable para el motor de scoring.

REFERENCE_RANGES = {
    # =========================================================
    # GLUCOSA / INSULINA / DERIVADOS
    # =========================================================
    "glucose_mg_dl": {
        "label": "Glucosa en ayunas",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": 70,
        "reference_high": 99,
        "target_default": 90,
        "low_flag": 70,
        "high_flag": 100,
        "critical_low": 55,
        "critical_high": 126,
        "notes": "Semilla ajustable para glucosa basal.",
    },
    "hba1c_pct": {
        "label": "HbA1c",
        "unit": "%",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 5.6,
        "target_default": 5.3,
        "low_flag": None,
        "high_flag": 5.7,
        "critical_low": None,
        "critical_high": 6.5,
        "notes": "Semilla ajustable para entorno glucémico crónico.",
    },
    "insulin_uIU_ml": {
        "label": "Insulina",
        "unit": "µIU/mL",
        "direction": "higher_worse",
        "reference_low": 2,
        "reference_high": 10,
        "target_default": 6,
        "low_flag": None,
        "high_flag": 10,
        "critical_low": None,
        "critical_high": 18,
        "notes": "Semilla funcional; no siempre disponible en práctica rutinaria.",
    },
    "homa_ir": {
        "label": "HOMA-IR",
        "unit": "ratio",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 1.5,
        "target_default": 1.2,
        "low_flag": None,
        "high_flag": 2.0,
        "critical_low": None,
        "critical_high": 3.0,
        "notes": "Derivado ajustable a partir de glucosa e insulina.",
    },
    "tg_hdl_ratio": {
        "label": "TG/HDL",
        "unit": "ratio",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 1.5,
        "target_default": 1.2,
        "low_flag": None,
        "high_flag": 2.0,
        "critical_low": None,
        "critical_high": 3.5,
        "notes": "Derivado útil para patrón metabólico-lipídico.",
    },

    # =========================================================
    # LÍPIDOS / DERIVADOS
    # =========================================================
    "chol_total_mg_dl": {
        "label": "Colesterol total",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 199,
        "target_default": 180,
        "low_flag": None,
        "high_flag": 200,
        "critical_low": None,
        "critical_high": 240,
        "notes": "Menos específico que LDL o no-HDL.",
    },
    "triglycerides_mg_dl": {
        "label": "Triglicéridos",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 149,
        "target_default": 100,
        "low_flag": None,
        "high_flag": 150,
        "critical_low": None,
        "critical_high": 200,
        "notes": "Variable muy accionable en patrón metabólico-lipídico.",
    },
    "ldl_mg_dl": {
        "label": "LDL",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 99,
        "target_default": 95,
        "low_flag": None,
        "high_flag": 100,
        "critical_low": None,
        "critical_high": 160,
        "notes": "Driver lipídico básico por defecto.",
    },
    "hdl_mg_dl": {
        "label": "HDL",
        "unit": "mg/dL",
        "direction": "lower_worse",
        "sex_specific": {
            "M": {
                "reference_low": 40,
                "reference_high": None,
                "target_default": 55,
                "low_flag": 40,
                "high_flag": None,
                "critical_low": 35,
                "critical_high": None,
            },
            "F": {
                "reference_low": 50,
                "reference_high": None,
                "target_default": 65,
                "low_flag": 50,
                "high_flag": None,
                "critical_low": 40,
                "critical_high": None,
            },
            "X": {
                "reference_low": 45,
                "reference_high": None,
                "target_default": 60,
                "low_flag": 45,
                "high_flag": None,
                "critical_low": 38,
                "critical_high": None,
            },
        },
        "notes": "Se ajusta por sexo; aislado pesa menos que TG/HDL.",
    },
    "non_hdl_mg_dl": {
        "label": "No-HDL",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 129,
        "target_default": 120,
        "low_flag": None,
        "high_flag": 130,
        "critical_low": None,
        "critical_high": 160,
        "notes": "Derivado útil como refuerzo del eje lipídico.",
    },

    # =========================================================
    # INFLAMACIÓN / INMUNE
    # =========================================================
    "hscrp_mg_l": {
        "label": "hsCRP",
        "unit": "mg/L",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 1.0,
        "target_default": 0.8,
        "low_flag": None,
        "high_flag": 3.0,
        "critical_low": None,
        "critical_high": 10.0,
        "notes": "Seed funcional para el eje inflamatorio.",
    },
    "nlr": {
        "label": "NLR",
        "unit": "ratio",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 2.0,
        "target_default": 1.8,
        "low_flag": None,
        "high_flag": 3.0,
        "critical_low": None,
        "critical_high": 5.0,
        "notes": "Derivado neutrófilos/linfocitos.",
    },
    "wbc_x10_3_mm3": {
        "label": "Leucocitos",
        "unit": "x10^3/mm³",
        "direction": "outside_range_worse",
        "reference_low": 4.0,
        "reference_high": 11.0,
        "target_default": 7.0,
        "low_flag": 4.0,
        "high_flag": 11.0,
        "critical_low": 3.0,
        "critical_high": 15.0,
        "notes": "Más contextual que decisivo en esta versión.",
    },
    "neut_abs_x10_3_mm3": {
        "label": "Neutrófilos (abs)",
        "unit": "x10^3/mm³",
        "direction": "higher_worse",
        "reference_low": 1.5,
        "reference_high": 7.0,
        "target_default": 3.5,
        "low_flag": None,
        "high_flag": 7.0,
        "critical_low": None,
        "critical_high": 10.0,
        "notes": "Se usa sobre todo a través de NLR.",
    },
    "lymph_abs_x10_3_mm3": {
        "label": "Linfocitos (abs)",
        "unit": "x10^3/mm³",
        "direction": "lower_worse",
        "reference_low": 1.0,
        "reference_high": 4.0,
        "target_default": 2.0,
        "low_flag": 1.0,
        "high_flag": None,
        "critical_low": 0.7,
        "critical_high": None,
        "notes": "Se usa sobre todo a través de NLR.",
    },
    "esr_mm_h": {
        "label": "VSG (ESR)",
        "unit": "mm/h",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 20,
        "target_default": 10,
        "low_flag": None,
        "high_flag": 20,
        "critical_low": None,
        "critical_high": 40,
        "notes": "Marcador más inespecífico.",
    },
    "fibrinogen_mg_dl": {
        "label": "Fibrinógeno",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": 200,
        "reference_high": 400,
        "target_default": 300,
        "low_flag": None,
        "high_flag": 400,
        "critical_low": None,
        "critical_high": 500,
        "notes": "Reservado como afinador inflamatorio.",
    },

    # =========================================================
    # HEMATOLOGÍA
    # =========================================================
    "rbc_x10_6_mm3": {
        "label": "Hematíes",
        "unit": "x10^6/mm³",
        "direction": "lower_worse",
        "sex_specific": {
            "M": {
                "reference_low": 4.5,
                "reference_high": 5.9,
                "target_default": 5.0,
                "low_flag": 4.5,
                "high_flag": None,
                "critical_low": 4.0,
                "critical_high": None,
            },
            "F": {
                "reference_low": 4.1,
                "reference_high": 5.1,
                "target_default": 4.6,
                "low_flag": 4.1,
                "high_flag": None,
                "critical_low": 3.7,
                "critical_high": None,
            },
            "X": {
                "reference_low": 4.3,
                "reference_high": 5.5,
                "target_default": 4.8,
                "low_flag": 4.3,
                "high_flag": None,
                "critical_low": 3.8,
                "critical_high": None,
            },
        },
        "notes": "Contexto eritrocitario.",
    },
    "hb_g_dl": {
        "label": "Hemoglobina",
        "unit": "g/dL",
        "direction": "lower_worse",
        "sex_specific": {
            "M": {
                "reference_low": 13.0,
                "reference_high": 18.0,
                "target_default": 14.5,
                "low_flag": 13.0,
                "high_flag": None,
                "critical_low": 11.5,
                "critical_high": None,
            },
            "F": {
                "reference_low": 12.0,
                "reference_high": 16.0,
                "target_default": 13.2,
                "low_flag": 12.0,
                "high_flag": None,
                "critical_low": 10.5,
                "critical_high": None,
            },
            "X": {
                "reference_low": 12.5,
                "reference_high": 17.0,
                "target_default": 13.8,
                "low_flag": 12.5,
                "high_flag": None,
                "critical_low": 11.0,
                "critical_high": None,
            },
        },
        "notes": "Driver funcional central del eje hematológico.",
    },
    "hct_pct": {
        "label": "Hematocrito",
        "unit": "%",
        "direction": "lower_worse",
        "sex_specific": {
            "M": {
                "reference_low": 41,
                "reference_high": 53,
                "target_default": 46,
                "low_flag": 41,
                "high_flag": None,
                "critical_low": 35,
                "critical_high": None,
            },
            "F": {
                "reference_low": 36,
                "reference_high": 46,
                "target_default": 41,
                "low_flag": 36,
                "high_flag": None,
                "critical_low": 31,
                "critical_high": None,
            },
            "X": {
                "reference_low": 38,
                "reference_high": 50,
                "target_default": 43,
                "low_flag": 38,
                "high_flag": None,
                "critical_low": 33,
                "critical_high": None,
            },
        },
        "notes": "Apoyo al patrón hematológico.",
    },
    "mcv_fl": {
        "label": "MCV",
        "unit": "fL",
        "direction": "outside_range_worse",
        "reference_low": 80,
        "reference_high": 100,
        "target_default": 90,
        "low_flag": 80,
        "high_flag": 100,
        "critical_low": 75,
        "critical_high": 105,
        "notes": "Muy útil para perfilar micro/macro.",
    },
    "rdw_pct": {
        "label": "RDW",
        "unit": "%",
        "direction": "higher_worse",
        "reference_low": 11.5,
        "reference_high": 14.5,
        "target_default": 13.0,
        "low_flag": None,
        "high_flag": 14.5,
        "critical_low": None,
        "critical_high": 15.5,
        "notes": "Muy dependiente del laboratorio; seed ajustable.",
    },
    "ferritin_ng_ml": {
        "label": "Ferritina",
        "unit": "ng/mL",
        "direction": "lower_worse",
        "sex_specific": {
            "M": {
                "reference_low": 30,
                "reference_high": 400,
                "target_default": 80,
                "low_flag": 30,
                "high_flag": None,
                "critical_low": 15,
                "critical_high": None,
            },
            "F": {
                "reference_low": 13,
                "reference_high": 150,
                "target_default": 50,
                "low_flag": 20,
                "high_flag": None,
                "critical_low": 15,
                "critical_high": None,
            },
            "X": {
                "reference_low": 20,
                "reference_high": 250,
                "target_default": 60,
                "low_flag": 20,
                "high_flag": None,
                "critical_low": 15,
                "critical_high": None,
            },
        },
        "notes": "Reserva de hierro; muy accionable.",
    },
    "iron_ug_dl": {
        "label": "Hierro",
        "unit": "µg/dL",
        "direction": "lower_worse",
        "reference_low": 60,
        "reference_high": 170,
        "target_default": 100,
        "low_flag": 60,
        "high_flag": None,
        "critical_low": 40,
        "critical_high": None,
        "notes": "Variable contextual; menos robusta aislada.",
    },
    "transferrin_mg_dl": {
        "label": "Transferrina",
        "unit": "mg/dL",
        "direction": "outside_range_worse",
        "reference_low": 200,
        "reference_high": 360,
        "target_default": 280,
        "low_flag": 200,
        "high_flag": 360,
        "critical_low": 170,
        "critical_high": 400,
        "notes": "Afinador para etapas siguientes.",
    },
    "transferrin_sat_pct": {
        "label": "Sat. transferrina",
        "unit": "%",
        "direction": "lower_worse",
        "reference_low": 20,
        "reference_high": 50,
        "target_default": 30,
        "low_flag": 20,
        "high_flag": None,
        "critical_low": 15,
        "critical_high": None,
        "notes": "Muy útil para versiones posteriores del eje hierro.",
    },
    "tibc_ug_dl": {
        "label": "TIBC",
        "unit": "µg/dL",
        "direction": "outside_range_worse",
        "reference_low": 250,
        "reference_high": 450,
        "target_default": 330,
        "low_flag": 250,
        "high_flag": 450,
        "critical_low": 220,
        "critical_high": 500,
        "notes": "Afinador del patrón de hierro.",
    },
    "vitb12_pg_ml": {
        "label": "Vitamina B12",
        "unit": "pg/mL",
        "direction": "lower_worse",
        "reference_low": 180,
        "reference_high": 914,
        "target_default": 450,
        "low_flag": 200,
        "high_flag": None,
        "critical_low": 150,
        "critical_high": None,
        "notes": "Afinador prudente del dominio hematológico.",
    },
    "folate_ng_ml": {
        "label": "Folato",
        "unit": "ng/mL",
        "direction": "lower_worse",
        "reference_low": 4.0,
        "reference_high": None,
        "target_default": 7.0,
        "low_flag": 4.0,
        "high_flag": None,
        "critical_low": 3.0,
        "critical_high": None,
        "notes": "Afinador prudente del dominio hematológico.",
    },

    # =========================================================
    # HÍGADO
    # =========================================================
    "alt_u_l": {
        "label": "ALT",
        "unit": "U/L",
        "direction": "higher_worse",
        "reference_low": 4,
        "reference_high": 36,
        "target_default": 22,
        "low_flag": None,
        "high_flag": 40,
        "critical_low": None,
        "critical_high": 60,
        "notes": "Driver hepático básico.",
    },
    "ast_u_l": {
        "label": "AST",
        "unit": "U/L",
        "direction": "higher_worse",
        "reference_low": 8,
        "reference_high": 48,
        "target_default": 22,
        "low_flag": None,
        "high_flag": 40,
        "critical_low": None,
        "critical_high": 60,
        "notes": "Complementa ALT.",
    },
    "ggt_u_l": {
        "label": "GGT",
        "unit": "U/L",
        "direction": "higher_worse",
        "reference_low": 5,
        "reference_high": 40,
        "target_default": 20,
        "low_flag": None,
        "high_flag": 40,
        "critical_low": None,
        "critical_high": 80,
        "notes": "Muy útil en carga hepato-metabólica.",
    },
    "alp_u_l": {
        "label": "ALP",
        "unit": "U/L",
        "direction": "higher_worse",
        "reference_low": 44,
        "reference_high": 120,
        "target_default": 80,
        "low_flag": None,
        "high_flag": 120,
        "critical_low": None,
        "critical_high": 180,
        "notes": "Modulador del dominio hepático.",
    },
    "bilirubin_total_mg_dl": {
        "label": "Bilirrubina total",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": 0.1,
        "reference_high": 1.2,
        "target_default": 0.7,
        "low_flag": None,
        "high_flag": 1.3,
        "critical_low": None,
        "critical_high": 2.0,
        "notes": "Más contextual para este caso de uso.",
    },

    # =========================================================
    # RIÑÓN
    # =========================================================
    "creatinine_mg_dl": {
        "label": "Creatinina",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "sex_specific": {
            "M": {
                "reference_low": 0.7,
                "reference_high": 1.3,
                "target_default": 0.95,
                "low_flag": None,
                "high_flag": 1.3,
                "critical_low": None,
                "critical_high": 1.6,
            },
            "F": {
                "reference_low": 0.5,
                "reference_high": 0.95,
                "target_default": 0.75,
                "low_flag": None,
                "high_flag": 0.95,
                "critical_low": None,
                "critical_high": 1.2,
            },
            "X": {
                "reference_low": 0.6,
                "reference_high": 1.1,
                "target_default": 0.85,
                "low_flag": None,
                "high_flag": 1.1,
                "critical_low": None,
                "critical_high": 1.4,
            },
        },
        "notes": "Proxy renal básico; mejor con eGFR.",
    },
    "egfr_ml_min_1_73m2": {
        "label": "eGFR",
        "unit": "mL/min/1.73m²",
        "direction": "lower_worse",
        "reference_low": 60,
        "reference_high": None,
        "target_default": 95,
        "low_flag": 60,
        "high_flag": None,
        "critical_low": 45,
        "critical_high": None,
        "notes": "Driver renal principal si está disponible.",
    },
    "uric_acid_mg_dl": {
        "label": "Ácido úrico",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": None,
        "reference_high": 6.0,
        "target_default": 5.2,
        "low_flag": None,
        "high_flag": 7.0,
        "critical_low": None,
        "critical_high": 8.0,
        "notes": "Apoyo renal-metabólico útil.",
    },
    "urea_mg_dl": {
        "label": "Urea",
        "unit": "mg/dL",
        "direction": "higher_worse",
        "reference_low": 15,
        "reference_high": 40,
        "target_default": 28,
        "low_flag": None,
        "high_flag": 40,
        "critical_low": None,
        "critical_high": 60,
        "notes": "Más contextual que decisiva.",
    },
}
